# Generated by Django 3.1.1 on 2021-05-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='s3pic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
