# Generated by Django 3.1.1 on 2021-05-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_s3pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='s3pic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picdata',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
