# Generated by Django 3.1.1 on 2021-05-29 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20210526_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follow',
            field=models.ManyToManyField(related_name='follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
