# Generated by Django 3.1.1 on 2021-05-29 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_userprofile_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, related_name='follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
