# Generated by Django 3.1.1 on 2021-05-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
